version: '3.9'

services:
  node:
    # image: node:16-alpine
    image: node_npm8.12.1
    build:
      context: ./
      dockerfile: Dockerfile.node
    working_dir: /home/node/app
    command: /bin/sh
    user: ${U:-1000}:${G:-1000}
    tty: true
    stdin_open: true
    stop_signal: SIGKILL
    restart: unless-stopped
    environment:
      PORT: ${PORT:-3000}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - ./:/home/node/app

  proxy:
    build: ./nginx
    volumes:
      - ./nginx:/nginx
    ports:
      - 443:443
    links:
      - 'node'
    depends_on:
      - node
